import { upload } from '@vercel/blob/client';
export const dynamic = 'force-dynamic';
async function uploadFile() {
  if (!file) return;

  setLoading(true);

  try {
    const blob = await upload(file.name, file, {
      access: 'public',
      handleUploadUrl: '/api/vercel/blob', // auto-generated by Vercel
      maximumSize: 500 * 1024 * 1024, // 500MB
    });

    setUrl(blob.url);
  } catch (err) {
    alert('Upload failed');
    console.error(err);
  }

  setLoading(false);
}

  // 1) Get signed upload URL
  const res = await fetch('/api/blob', { method: 'POST' });
  const { url } = await res.json();

  // 2) Upload directly to Blob
  const uploadRes = await fetch(url, {
    method: 'PUT',
    body: file,
    headers: {
      'Content-Type': file.type,
    },
  });

  if (!uploadRes.ok) {
    alert('Upload failed');
    setLoading(false);
    return;
  }

  // 3) FINAL FILE URL (strip query params)
  const cleanUrl = url.split('?')[0];
  setUrl(cleanUrl);

  setLoading(false);
}
